version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: admin-panel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: admin_panel
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: admin_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - admin-panel-network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: admin-panel-backend
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: admin_panel
      DB_USERNAME: admin_user
      DB_PASSWORD: admin_password
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - admin-panel-network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: admin-panel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - admin-panel-network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: admin-panel-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    networks:
      - admin-panel-network

volumes:
  db_data:
    driver: local

networks:
  admin-panel-network:
    driver: bridge
