version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: admin-panel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-admin_panel}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_USER: ${DB_USERNAME:-admin_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - admin-panel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel Backend with Nginx
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: admin-panel-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:80"
    environment:
      APP_NAME: ${APP_NAME:-AdminPanel}
      APP_ENV: ${APP_ENV:-production}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost:8000}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-admin_panel}
      DB_USERNAME: ${DB_USERNAME:-admin_user}
      DB_PASSWORD: ${DB_PASSWORD:-admin_password}
      LOG_CHANNEL: ${LOG_CHANNEL:-stderr}
      SESSION_DRIVER: ${SESSION_DRIVER:-database}
      CACHE_STORE: ${CACHE_STORE:-database}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - admin-panel-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: admin-panel-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000/api}
    depends_on:
      - backend
    networks:
      - admin-panel-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db_data:
    driver: local

networks:
  admin-panel-network:
    driver: bridge
