name: admin-panel-laravel-nextjs
region: nyc

# Database
databases:
  - name: db
    engine: MYSQL
    version: "8"
    production: true
    cluster_name: admin-panel-db

# Backend Service (Laravel API)
services:
  - name: backend
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    github:
      repo: somkheartk/admin-panel-laravel-tailwincss-nextjs-mui
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 9000
    routes:
      - path: /api
    envs:
      - key: APP_NAME
        value: AdminPanel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        scope: RUN_TIME
        value: ${db.HOSTNAME}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${db.PORT}
      - key: DB_DATABASE
        scope: RUN_TIME
        value: ${db.DATABASE}
      - key: DB_USERNAME
        scope: RUN_TIME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        scope: RUN_TIME
        value: ${db.PASSWORD}
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database

  # Frontend Service (Next.js)
  - name: frontend
    dockerfile_path: frontend/Dockerfile
    source_dir: frontend
    github:
      repo: somkheartk/admin-panel-laravel-tailwincss-nextjs-mui
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.PUBLIC_URL}/api
